#!/usr/bin/env bash

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ]; then
    exec gosu $WWWUSER "$@"
else
    # make backups folder
    # mkdir -p storage/backups

    # # setup application
    # composer update
    # composer install
    # composer dump-autoload

    # # run npm
    # npm install
    # npm run production

    # # run laravel commands
    # php artisan storage:link
    # # php artisan backup:database
    # php artisan optimize:clear
    # php artisan migrate --force
    # php artisan db:seed --force
    # php artisan optimize

    # restart crontab
    crontab /var/cron.schedule
    service cron restart

    # start supervisor
    # service supervisord stop
    # service supervisord start
    /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf

    # start apache server
    apachectl -D FOREGROUND
fi
